server:
  port: 9001

spring:
  application:
    name: demo-01
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.40.238:8848

#  boot:
#    admin:
#      client:
#        url: http://localhost:9000
#        username: root
#        password: root

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露所有的 actuator 端点信息重
  endpoint:
    health:
      show-details: always


logging:
  file: /Users/zhangsan/Downloads/spring-boot-admin-client.log #指向日志文件地址